# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-12-21 18:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login_and_registration_app', '0001_initial'),
        ('friends_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Requests',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('recieving_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recieved_requests', to='login_and_registration_app.Users')),
                ('sending_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_requests', to='login_and_registration_app.Users')),
            ],
        ),
    ]
